In [1]:
import numpy as np

In [2]:
x =  np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],
               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],
               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])

# Axis 0 Input
<b>

<font color='#01befe'>0</font>,<font color='#ff7d00'>1</font>,<font color='#adff02'>2</font>  
<font color='#8f00ff'>3</font>,<font color='#ff006d'>4</font>,<font color='#ffdd00'>5</font>  
<font color='black'>6</font>,<font color='brown'>7</font>,<font color='grey'>8</font>  

<font color='#01befe'>9</font>,<font color='#ff7d00'>10</font>,<font color='#adff02'>11</font>  
<font color='#8f00ff'>12</font>,<font color='#ff006d'>13</font>,<font color='#ffdd00'>14</font>  
<font color='black'>15</font>,<font color='brown'>16</font>,<font color='grey'>17</font>  

<font color='#01befe'>18</font>,<font color='#ff7d00'>19</font>,<font color='#adff02'>20</font>  
<font color='#8f00ff'>21</font>,<font color='#ff006d'>22</font>,<font color='#ffdd00'>23</font>  
<font color='black'>24</font>,<font color='brown'>25</font>,<font color='grey'>26</font>  

</b>

## Result
<b>
<font color='#01befe'>27</font>,<font color='#ff7d00'>30</font>,<font color='#adff02'>33</font>  
    
<font color='#8f00ff'>36</font>,<font color='#ff006d'>39</font>,<font color='#ffdd00'>42</font>  
    
<font color='black'>45</font>,<font color='brown'>48</font>,<font color='grey'>51</font>  
</b>

In [3]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

# Axis 1 Input
<b>

<font color='#01befe'>0</font>,<font color='#ff7d00'>1</font>,<font color='#adff02'>2</font>  
<font color='#01befe'>3</font>,<font color='#ff7d00'>4</font>,<font color='#adff02'>5</font>  
<font color='#01befe'>6</font>,<font color='#ff7d00'>7</font>,<font color='#adff02'>8</font>  

<font color='#8f00ff'>9</font>,<font color='#ff006d'>10</font>,<font color='#ffdd00'>11</font>  
<font color='#8f00ff'>12</font>,<font color='#ff006d'>13</font>,<font color='#ffdd00'>14</font>  
<font color='#8f00ff'>15</font>,<font color='#ff006d'>16</font>,<font color='#ffdd00'>17</font>  

<font color='black'>18</font>,<font color='brown'>19</font>,<font color='grey'>20</font>  
<font color='black'>21</font>,<font color='brown'>22</font>,<font color='grey'>23</font>  
<font color='black'>24</font>,<font color='brown'>25</font>,<font color='grey'>26</font>  

</b>

## Result
<b>
<font color='#01befe'>9</font>,<font color='#ff7d00'>12</font>,<font color='#adff02'>15</font>  
    
<font color='#8f00ff'>36</font>,<font color='#ff006d'>39</font>,<font color='#ffdd00'>42</font>  
    
<font color='black'>63</font>,<font color='brown'>66</font>,<font color='grey'>69</font>  
</b>

In [4]:
x.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

# Axis 2 Input
<b>

<font color='#01befe'>0</font>,<font color='#01befe'>1</font>,<font color='#01befe'>2</font>  
<font color='#ff7d00'>3</font>,<font color='#ff7d00'>4</font>,<font color='#ff7d00'>5</font>  
<font color='#adff02'>6</font>,<font color='#adff02'>7</font>,<font color='#adff02'>8</font> 

<font color='#8f00ff'>9</font>,<font color='#8f00ff'>10</font>,<font color='#8f00ff'>11</font>  
<font color='#ff006d'>12</font>,<font color='#ff006d'>13</font>,<font color='#ff006d'>14</font>  
<font color='#ffdd00'>15</font>,<font color='#ffdd00'>16</font>,<font color='#ffdd00'>17</font>  

<font color='black'>18</font>,<font color='black'>19</font>, <font color='black'>20</font>  
<font color='brown'>21</font>,<font color='brown'>22</font>,<font color='brown'>23</font>  
<font color='grey'>24</font>,<font color='grey'>26</font>,<font color='grey'>26</font>  

</b>

## Result
<b>
<font color='#01befe'>3</font>,<font color='#ff7d00'>12</font>,<font color='#adff02'>21</font>  
    
<font color='#8f00ff'>30</font>,<font color='#ff006d'>39</font>,<font color='#ffdd00'>48</font>  
    
<font color='black'>57</font>,<font color='brown'>66</font>,<font color='grey'>75</font>  
</b>

In [5]:
x.sum(axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])